// GENERATED from PRIVACY.md in the rill-launcher repo by tools/render-policy.py.
// Do not edit here: the policy lives beside the code it describes, so that a change
// to what the app reads and a change to what the policy claims are the same commit.
export const rillPrivacyHtml = `<p>Rill is a home screen. It shows the apps on your phone, your notifications, your next calendar events, the weather and what is playing. This page says exactly what it reads to do that, what leaves the phone, and what does not. It is written to be checked against the code.</p>
<p>Rill is published by <strong>Bilco Works</strong>, Calgary, Canada.</p>
<p>There are two builds of Rill. The <strong>store build</strong> is the one on Google Play. The <strong>personal build</strong> is a private, sideloaded build for the developer's own phone and is not distributed. Where they differ it is said below; everything else applies to both.</p>
<p>Rill has no accounts, no analytics, no advertising, no crash reporting service and no servers of its own that the store build talks to.</p>
<h2>What Rill reads, and why</h2>
<table><thead><tr><th>What</th><th>Why</th><th>Stays on the phone?</th></tr></thead><tbody><tr><td>The list of installed apps, their names and icons</td><td>It is a launcher: this is the list.</td><td>Yes.</td></tr><tr><td>Which apps you open from Rill, and when</td><td>The "recently opened" section, and the order of your favourites.</td><td>Yes, in Rill's own storage.</td></tr><tr><td>Notifications (with <strong>notification access</strong>, which you grant once)</td><td>To show each notification under the app that sent it, and to dismiss or open it from there. Also how Rill knows what is playing, for the media row.</td><td>Yes. Notifications are read from the system and drawn on screen; Rill keeps no copy.</td></tr><tr><td>Calendar (with the <strong>calendar</strong> permission)</td><td>The next two events of the coming day, under the clock. Titles, start times and whether an event is all-day (all-day events are skipped).</td><td>Yes.</td></tr><tr><td>Approximate location (with the <strong>location</strong> permission)</td><td>The weather. Rill uses the phone's *last known* coarse location and never asks for a fresh fix.</td><td><strong>No — see below.</strong></td></tr><tr><td>A photo you pick for a theme, or a font you import</td><td>To draw it behind the list, or to letter the list with it.</td><td>Yes. A copy is kept in Rill's private storage; deleting the theme or the font deletes the copy.</td></tr><tr><td>A data line you add under the date (Rill Collection)</td><td>A countdown or a fixed line stays on the phone. A <strong>Home Assistant</strong> line asks the Home Assistant server *you* typed in for one entity's state, on every return to the home screen, using the access token *you* typed in.</td><td>Countdown and text lines: yes. A Home Assistant line: <strong>no — see below.</strong></td></tr><tr><td>A widget you add to the home list</td><td>Rill asks the system to draw that app's own widget in the space you gave it, by an id the system issued. Rill does not read what the widget shows, and cannot - the drawing is done by the system on the providing app's behalf.</td><td>Yes. Rill stores only the id and the height.</td></tr><tr><td>Your settings</td><td>To remember them.</td><td>Yes, unless you export them yourself.</td></tr><tr><td>A crash log, if Rill ever crashes</td><td>So a crash can be looked at from Settings.</td><td>Yes.</td></tr></tbody></table>
<p>Every permission is optional. Rill explains what it will read before it asks, and a refused permission simply means that part of the header stays empty.</p>
<h2>What leaves the phone</h2>
<p><strong>Weather.</strong> When you have allowed location, Rill sends a latitude and longitude to Open-Meteo (<code>api.open-meteo.com</code>) to fetch the forecast, over HTTPS. Rill sends nothing else anywhere on its own; the one other thing that can leave the phone is a data line you set up yourself, described next. Open-Meteo's own policy is at <a href="https://open-meteo.com/en/terms.">https://open-meteo.com/en/terms.</a> Rill sends no account or device identifier with the request and keeps no record of where you were.</p>
<p><strong>Purchases (store build).</strong> Unlocking the Rill Collection goes through Google Play Billing. Rill asks Google Play whether the Collection is owned and shows the price Play reports; the purchase itself, and any personal data involved in it, is handled by Google Play under Google's terms. Rill receives no name, email or payment details.</p>
<p><strong>A Home Assistant line (Rill Collection).</strong> If you add one, Rill sends a request for the entity you named, carrying the long-lived access token you typed, to the Home Assistant address you typed - over HTTPS only, and to no other server. It is your server, your token and your address; Rill stores the token in its private storage, never logs it, and sends it nowhere else. Removing the line removes the token. A settings backup you export yourself ("Save to a file") contains your lines, token included - treat that file as you would the token. Countdown and text lines never leave the phone.</p>
<p><strong>Nothing else.</strong> No app list, no notification, no calendar entry, no photo and no font ever leaves the phone.</p>
<h2>The personal build only</h2>
<p>The personal build is not on any store. In addition to the above it:</p>
<ul><li>checks a private update server for new versions and downloads them from it;</li><li>fetches a summary of the developer's own investment account from that same server,</li></ul>
<p>  identified by a key typed into Settings.</p>
<p>Neither of these exists in the store build; the code for them is not compiled into it.</p>
<h2>Storage and deletion</h2>
<p>Everything Rill keeps is in its private app storage on the phone. Uninstalling Rill deletes all of it. There is nothing to delete anywhere else, because nothing is kept anywhere else.</p>
<h2>Children</h2>
<p>Rill is a general-purpose launcher and is not directed at children.</p>
<h2>Changes and contact</h2>
<p>This policy changes only when what the app reads or sends changes, and the change will be described here. Questions: rill@bilcoworks.com.</p>`
